-- MASTER SUPABASE SETUP SCRIPT
-- Run this in the Supabase SQL Editor to reset and set up the entire database.

-- 1. CLEANUP (Drop existing tables to start fresh)
DROP TABLE IF EXISTS public.enrollments;
DROP TABLE IF EXISTS public.lessons;
DROP TABLE IF EXISTS public.courses;

-- 2. CREATE TABLES

-- Courses Table (Merged Schema)
CREATE TABLE public.courses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    title text NOT NULL,
    description text,
    image_url text NOT NULL,
    category text NOT NULL, -- 'highlight', 'popular', 'next_evolution', 'continue_watching'
    is_locked boolean DEFAULT true,
    price numeric DEFAULT 0.00,
    instructor text DEFAULT 'Nomad Academy',
    rating numeric DEFAULT 5.0,
    reviews_count integer DEFAULT 0,
    sales_copy text,
    match_score text -- '98%'
);

-- Lessons Table
CREATE TABLE public.lessons (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint REFERENCES public.courses(id) ON DELETE CASCADE,
    title text NOT NULL,
    description text,
    video_url text NOT NULL,
    position integer DEFAULT 1,
    duration text DEFAULT '10:00',
    is_locked boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enrollments Table
CREATE TABLE public.enrollments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users NOT NULL,
    course_id bigint REFERENCES public.courses(id) NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, course_id)
);

-- 3. ENABLE SECURITY (RLS)

ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;

-- 4. CREATE POLICIES (Permissions)

-- Public can view courses
CREATE POLICY "Public courses are viewable by everyone" 
ON public.courses FOR SELECT USING (true);

-- Public can view lessons (logic handled by is_locked in frontend usually, but here checking locked status)
-- For simplicity in this MVP, we allow select to everyone, but content is gated by UI.
CREATE POLICY "Lessons are viewable by everyone" 
ON public.lessons FOR SELECT USING (true);

-- Admin access (In a real app, you'd check for admin role. For now, open for MVP functionality)
CREATE POLICY "Enable insert for courses" ON public.courses FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for courses" ON public.courses FOR UPDATE USING (true);
CREATE POLICY "Enable delete for courses" ON public.courses FOR DELETE USING (true);

CREATE POLICY "Enable insert for lessons" ON public.lessons FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for lessons" ON public.lessons FOR UPDATE USING (true);
CREATE POLICY "Enable delete for lessons" ON public.lessons FOR DELETE USING (true);

-- Enrollments: Users view their own
CREATE POLICY "Users view their own enrollments" 
ON public.enrollments FOR SELECT TO authenticated USING (auth.uid() = user_id);

CREATE POLICY "Users can enroll" 
ON public.enrollments FOR INSERT TO authenticated WITH CHECK (true);


-- 5. SEED DATA (Initial Content)

-- Courses
INSERT INTO public.courses (title, description, image_url, category, is_locked, price, instructor, rating, reviews_count, match_score, sales_copy) VALUES
(
    'O Nômade Digital: Guia Completo', 
    'Aprenda o passo a passo para se libertar do escritório e trabalhar viajando o mundo.',
    'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=1000&auto=format&fit=crop',
    'highlight',
    false,
    0.00,
    'Rafael Barbosa',
    4.9,
    1240,
    '98%',
    'Inicie sua jornada agora gratuitamente.'
),
(
    'Mestres do Freelancing', 
    'Domine as plataformas de trabalho remoto e ganhe em dólar.',
    'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1000&auto=format&fit=crop',
    'next_evolution',
    true,
    297.00,
    'Equipe Nomad',
    4.8,
    850,
    '95%',
    'Aprenda a negociar como um profissional.'
),
(
    'Inglês para Nômades', 
    'Inglês prático para passar na imigração e fechar contratos.',
    'https://images.unsplash.com/photo-1543269865-cbf427effbad?q=80&w=1000&auto=format&fit=crop',
    'popular',
    true,
    147.00,
    'Sarah Teacher',
    4.7,
    300,
    '88%',
    'Nunca mais trave na hora de falar.'
),
(
    'Investimentos Globais', 
    'Proteja seu patrimônio investindo internacionalmente.',
    'https://images.unsplash.com/photo-1611974765215-e28ed4827628?q=80&w=1000&auto=format&fit=crop',
    'next_evolution',
    true,
    497.00,
    'Paulo Finance',
    5.0,
    150,
    '99%',
    'Crie renda passiva em dólar.'
);

-- Lessons for Course 1 (ID likely 1, but using subquery to be safe isn't supported easily in simple script, assuming ID 1 due to sequential insert on fresh table)
INSERT INTO public.lessons (course_id, title, description, video_url, position, is_locked) VALUES
(1, 'Introdução ao Nomadismo', 'O que é ser um nômade digital?', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 1, false),
(1, 'Planejamento Financeiro', 'Quanto custa viajar o mundo?', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 2, true),
(1, 'Equipamentos Essenciais', 'O que levar na mochila.', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 3, true);

-- Storage Setup Attempt (Might fail if extension not enabled, but worth a try syntax-wise if using Supabase SQL editor)
-- Note: Storage buckets usually need to be created via UI or specific API, but policies can be SQL.
-- INSERT INTO storage.buckets (id, name, public) VALUES ('videos', 'videos', true) ON CONFLICT DO NOTHING;
