-- 1. Create the courses table
CREATE TABLE IF NOT EXISTS public.courses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    title text NOT NULL,
    description text,
    image_url text NOT NULL,
    sales_copy text,
    is_locked boolean DEFAULT false,
    category text NOT NULL, -- 'highlight', 'continue_watching', 'next_evolution', 'popular'
    progress integer DEFAULT 0,
    match_score text
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy that allows everyone to read courses (public catalog)
CREATE POLICY "Public courses are viewable by everyone" 
ON public.courses FOR SELECT 
USING (true);

-- 4. Seed Data (Initial Content)

-- Highlights (Billboard)
INSERT INTO public.courses (title, description, image_url, is_locked, sales_copy, category) VALUES
(
    'Nômade Digital',
    'Acompanhe a jornada completa de zero a 100 países. Descubra como criar liberdade geográfica e financeira em tempo recorde.',
    '/hero-nomad-v2.jpg',
    false,
    'Você já tem acesso! Sua jornada para a liberdade geográfica já começou. Continue assistindo para dominar as técnicas de produtividade em trânsito.',
    'highlight'
),
(
    'Inglês para o Mundo',
    'O método definitivo para destravar seu inglês e se comunicar em qualquer lugar do planeta sem medo.',
    'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1600&q=80',
    true,
    'Imagine pedir seu café em Paris ou negociar um tuk-tuk na Tailândia com total confiança. O mundo se abre quando você fala a língua dele. Desbloqueie agora e destrave sua comunicação global.',
    'highlight'
),
(
    'Filmmaker Pro',
    'Aprenda a capturar e editar vídeos cinematográficos usando apenas o seu equipamento atual.',
    'https://images.unsplash.com/photo-1535016120720-40c6874c3b1c?auto=format&fit=crop&w=1600&q=80',
    true,
    'Suas viagens merecem mais do que stories de 24 horas. Crie narrativas visuais cinematográficas que inspiram, engajam e podem até financiar sua próxima passagem aérea.',
    'highlight'
);

-- Continue Watching (Meus Cursos)
INSERT INTO public.courses (title, image_url, progress, is_locked, category) VALUES
('Torne-se um Nômade Digital', 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800', 35, false, 'continue_watching'),
('Inglês para Viagem', 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800', 10, false, 'continue_watching');

-- Next Evolution (Funnel)
INSERT INTO public.courses (title, image_url, match_score, is_locked, sales_copy, category) VALUES
('Marketing Digital Avançado', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800', '98%', true, 'Domine o mercado digital e escale seus negócios.', 'next_evolution'),
('Edição de Vídeo Pro', 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=800', '95%', true, 'Edite como um profissional de cinema.', 'next_evolution'),
('Investimentos Globais', 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800', '90%', true, 'Aprenda a investir seu dinheiro em qualquer lugar do mundo.', 'next_evolution');

-- Popular (Recommendations)
INSERT INTO public.courses (title, image_url, match_score, is_locked, sales_copy, category) VALUES
('Design com Figma', 'https://images.unsplash.com/photo-1587614382346-4ec70e388b28?w=800', '85%', true, 'Crie interfaces incríveis com a ferramenta mais usada do mundo.', 'popular'),
('Setup YouTuber', 'https://images.unsplash.com/photo-1593697820928-601d4a0f44e6?w=800', '80%', true, 'Monte o estúdio perfeito em casa.', 'popular'),
('Fotografia Mobile', 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800', '75%', true, 'Tire fotos profissionais com seu celular.', 'popular');
