-- Tabela de Aulas (Lessons)
CREATE TABLE IF NOT EXISTS public.lessons (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint REFERENCES public.courses(id) ON DELETE CASCADE,
    title text NOT NULL,
    description text,
    video_url text NOT NULL,
    position integer DEFAULT 1,
    duration text DEFAULT '10:00',
    is_locked boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS
ALTER TABLE public.lessons ENABLE ROW LEVEL SECURITY;

-- Policies (Permissões)
-- 1. Leitura pública (para podermos testar, ou verificar is_locked no front)
CREATE POLICY "Lessons are viewable by everyone" ON public.lessons FOR SELECT USING (true);

-- 2. Escrita (Insert/Update) pública para testes (Admin)
CREATE POLICY "Enable insert for lessons" ON public.lessons FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for lessons" ON public.lessons FOR UPDATE USING (true);

-- Seed Data (Aulas de Exemplo para o curso ID 1 - Nômade Digital)
-- Certifique-se que o Curso ID 1 existe. Se não existir, crie-o antes ou ajuste o course_id.
INSERT INTO public.lessons (course_id, title, description, video_url, position, is_locked) VALUES
(1, 'Introdução ao Nomadismo', 'O que é ser um nômade digital?', 'https://www.youtube.com/embed/dQw4w9WgXcQ', 1, false),
(1, 'Planejamento Financeiro', 'Quanto custa viajar o mundo?', 'https://www.youtube.com/embed/dQw4w9WgXcQ', 2, true),
(1, 'Equipamentos Essenciais', 'O que levar na mochila.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', 3, true);
