-- 1. RESET: Apaga a tabela antiga se ela já existir (Para evitar o erro "already exists")
DROP TABLE IF EXISTS public.courses;

-- 2. CRIA a tabela do zero (Garante que as colunas estejam certas)
create table public.courses (
  id bigint generated by default as identity primary key,
  title text not null,
  instructor text not null,
  price numeric not null,
  rating numeric default 0,
  reviews_count integer default 0,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Habilita segurança (RLS)
alter table public.courses enable row level security;

-- 4. Cria política de leitura (Pública)
create policy "Courses are viewable by everyone" 
on public.courses for select 
using ( true );

-- 5. Cria política de escrita (Instrutores Autenticados)
create policy "Instructors can insert courses" 
on public.courses for insert 
to authenticated 
with check ( true );

-- 6. Insere dados de exemplo com IMAGENS NOVAS (URLs corrigidas)
insert into public.courses (title, instructor, price, rating, reviews_count, image_url) values
('Torne-se um Nômade Digital: O Guia Completo 2024', 'Rafael Barbosa', 49.90, 4.8, 1250, 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80'),
('Inglês para Viagem e Negócios', 'Sarah Jenkins', 29.90, 4.5, 850, 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80'),
('Fotografia com Smartphone para Criadores', 'Ana Costa', 39.90, 4.9, 2100, 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80'),
('Gestão Financeira para Freelancers', 'Pedro Silva', 59.90, 4.7, 530, 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&w=800&q=80');
