-- Tabela de Matrículas (Quem comprou o quê)
create table if not exists enrollments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  course_id bigint references courses not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, course_id)
);

-- Segurança (RLS)
alter table enrollments enable row level security;

-- Aluno vê suas próprias matrículas
create policy "Alunos veem suas matriculas" 
on enrollments for select 
to authenticated 
using (auth.uid() = user_id);

-- Admin/Sistema pode matricular (via API de pagamento)
create policy "Sistema pode criar matriculas" 
on enrollments for insert 
to authenticated 
with check (true); 
-- Nota: Em produção, ideal restringir insert apenas para service_role ou webhook
